//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrammarCheck {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrammarCheck.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The POST request requires a &apos;text&apos; field.
        /// </summary>
        internal static string Bad_request_grammar {
            get {
                return ResourceManager.GetString("Bad_request_grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either username or password is incorrect..
        /// </summary>
        internal static string incorrect_credentials {
            get {
                return ResourceManager.GetString("incorrect_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry you are not authorized.
        /// </summary>
        internal static string not_authorize {
            get {
                return ResourceManager.GetString("not_authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password.
        /// </summary>
        internal static string password_required {
            get {
                return ResourceManager.GetString("password_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been logged in successfully.
        /// </summary>
        internal static string successful_login {
            get {
                return ResourceManager.GetString("successful_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again.
        /// </summary>
        internal static string try_again {
            get {
                return ResourceManager.GetString("try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter username.
        /// </summary>
        internal static string username_required {
            get {
                return ResourceManager.GetString("username_required", resourceCulture);
            }
        }
    }
}
